version = 1

test_patterns = ["src/**/*.test.ts"]

exclude_patterns = [
  ".typedoc-out/**",
  "templates/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "vitest",
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "test-coverage"

  [analyzers.meta]
