version = 1

exclude_patterns = [
  ".typedoc-out/**",
  "templates/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "vitest",
    "browser",
    "nodejs"
  ]
  skip_rules = [
    "JS-T1001"
  ]

[[analyzers]]
name = "test-coverage"

  [analyzers.meta]
