/**
 * AUTO-GENERATED by transform-graph Swift CLI using SwiftSyntax
 * Do not edit manually - regenerate when XcodeGraph updates
 *
 * Run: swift run transform-graph --source-dir <path-to-xcodegraph>
 */

/* eslint-disable @typescript-eslint/no-empty-object-type */

import type { GraphData, GraphEdge, GraphNode } from '@/shared/schemas/graph.schema';
import { NodeType, Origin, Platform } from '@/shared/schemas/graph.schema';

// =============================================================================
// Raw Types (Generated from XcodeGraph Swift sources)
// =============================================================================

export interface RawGraphDependency_xcframework {
  xcframework: {
    _0: RawXCFramework;
  };
}

export interface RawGraphDependency_framework {
  framework: {
    path: string;
    binaryPath: string;
    dsymPath: string;
    bcsymbolmapPaths: string[];
    linking: unknown;
    architectures: unknown[];
    status: unknown;
  };
}

export interface RawGraphDependency_library {
  library: {
    path: string;
    publicHeaders: string;
    linking: unknown;
    architectures: unknown[];
    swiftModuleMap: string;
  };
}

export interface RawGraphDependency_macro {
  macro: {
    path: string;
  };
}

export interface RawGraphDependency_bundle {
  bundle: {
    path: string;
  };
}

export interface RawGraphDependency_packageProduct {
  packageProduct: {
    path: string;
    product: string;
    type: RawPackageProductType;
  };
}

export interface RawGraphDependency_target {
  target: {
    name: string;
    path: string;
    status: unknown;
  };
}

export interface RawGraphDependency_sdk {
  sdk: {
    name: string;
    path: string;
    status: unknown;
    source: RawSDKSource;
  };
}

export type RawGraphDependency =
  | RawGraphDependency_xcframework
  | RawGraphDependency_framework
  | RawGraphDependency_library
  | RawGraphDependency_macro
  | RawGraphDependency_bundle
  | RawGraphDependency_packageProduct
  | RawGraphDependency_target
  | RawGraphDependency_sdk;

export interface RawPackageProductType_runtime {
  runtime: Record<string, never>;
}

export interface RawPackageProductType_runtimeEmbedded {
  runtimeEmbedded: Record<string, never>;
}

export interface RawPackageProductType_plugin {
  plugin: Record<string, never>;
}

export interface RawPackageProductType_macro {
  macro: Record<string, never>;
}

export type RawPackageProductType =
  | RawPackageProductType_runtime
  | RawPackageProductType_runtimeEmbedded
  | RawPackageProductType_plugin
  | RawPackageProductType_macro;

export interface RawProjectType_local {
  local: Record<string, never>;
}

export interface RawProjectType_external {
  external: {
    hash: string;
  };
}

export type RawProjectType = RawProjectType_local | RawProjectType_external;

export interface RawPlatform_iOS {
  iOS: Record<string, never>;
}

export interface RawPlatform_macOS {
  macOS: Record<string, never>;
}

export interface RawPlatform_tvOS {
  tvOS: Record<string, never>;
}

export interface RawPlatform_watchOS {
  watchOS: Record<string, never>;
}

export interface RawPlatform_visionOS {
  visionOS: Record<string, never>;
}

export type RawPlatform =
  | RawPlatform_iOS
  | RawPlatform_macOS
  | RawPlatform_tvOS
  | RawPlatform_watchOS
  | RawPlatform_visionOS;

export interface RawPackagePlatform_iOS {
  iOS: Record<string, never>;
}

export interface RawPackagePlatform_macCatalyst {
  macCatalyst: Record<string, never>;
}

export interface RawPackagePlatform_macOS {
  macOS: Record<string, never>;
}

export interface RawPackagePlatform_tvOS {
  tvOS: Record<string, never>;
}

export interface RawPackagePlatform_watchOS {
  watchOS: Record<string, never>;
}

export interface RawPackagePlatform_visionOS {
  visionOS: Record<string, never>;
}

export type RawPackagePlatform =
  | RawPackagePlatform_iOS
  | RawPackagePlatform_macCatalyst
  | RawPackagePlatform_macOS
  | RawPackagePlatform_tvOS
  | RawPackagePlatform_watchOS
  | RawPackagePlatform_visionOS;

export interface RawProduct_app {
  app: Record<string, never>;
}

export interface RawProduct_staticLibrary {
  staticLibrary: Record<string, never>;
}

export interface RawProduct_dynamicLibrary {
  dynamicLibrary: Record<string, never>;
}

export interface RawProduct_framework {
  framework: Record<string, never>;
}

export interface RawProduct_staticFramework {
  staticFramework: Record<string, never>;
}

export interface RawProduct_unitTests {
  unitTests: Record<string, never>;
}

export interface RawProduct_uiTests {
  uiTests: Record<string, never>;
}

export interface RawProduct_bundle {
  bundle: Record<string, never>;
}

export interface RawProduct_commandLineTool {
  commandLineTool: Record<string, never>;
}

export interface RawProduct_appExtension {
  appExtension: Record<string, never>;
}

export interface RawProduct_watch2App {
  watch2App: Record<string, never>;
}

export interface RawProduct_watch2Extension {
  watch2Extension: Record<string, never>;
}

export interface RawProduct_tvTopShelfExtension {
  tvTopShelfExtension: Record<string, never>;
}

export interface RawProduct_messagesExtension {
  messagesExtension: Record<string, never>;
}

export interface RawProduct_stickerPackExtension {
  stickerPackExtension: Record<string, never>;
}

export interface RawProduct_appClip {
  appClip: Record<string, never>;
}

export interface RawProduct_xpc {
  xpc: Record<string, never>;
}

export interface RawProduct_systemExtension {
  systemExtension: Record<string, never>;
}

export interface RawProduct_extensionKitExtension {
  extensionKitExtension: Record<string, never>;
}

export interface RawProduct_macro {
  macro: Record<string, never>;
}

export type RawProduct =
  | RawProduct_app
  | RawProduct_staticLibrary
  | RawProduct_dynamicLibrary
  | RawProduct_framework
  | RawProduct_staticFramework
  | RawProduct_unitTests
  | RawProduct_uiTests
  | RawProduct_bundle
  | RawProduct_commandLineTool
  | RawProduct_appExtension
  | RawProduct_watch2App
  | RawProduct_watch2Extension
  | RawProduct_tvTopShelfExtension
  | RawProduct_messagesExtension
  | RawProduct_stickerPackExtension
  | RawProduct_appClip
  | RawProduct_xpc
  | RawProduct_systemExtension
  | RawProduct_extensionKitExtension
  | RawProduct_macro;

export interface RawSDKSource_developer {
  developer: Record<string, never>;
}

export interface RawSDKSource_system {
  system: Record<string, never>;
}

export type RawSDKSource = RawSDKSource_developer | RawSDKSource_system;

export interface RawGraph {
  name: string;
  path: string;
  workspace: RawWorkspace;
  projects: unknown;
  packages: unknown;
  dependencies: unknown;
  dependencyConditions: unknown;
}

export interface RawXCFramework {
  path: string;
  infoPlist: unknown;
  linking: unknown;
  mergeable: boolean;
  status: unknown;
  swiftModules: string[];
  moduleMaps: string[];
  expectedSignature?: string;
  description: string;
}

export interface RawGraphEdge {
  from: RawGraphDependency;
  to: RawGraphDependency;
}

export interface RawGraphTarget {
  path: string;
  target: RawTarget;
  project: RawProject;
  debugDescription: string;
  description: string;
}

export interface RawProject {
  path: string;
  sourceRootPath: string;
  xcodeProjPath: string;
  name: string;
  organizationName?: string;
  classPrefix?: string;
  defaultKnownRegions?: string[];
  developmentRegion?: string;
  options: unknown;
  targets: unknown;
  packages: unknown[];
  schemes: unknown[];
  settings: unknown;
  filesGroup: unknown;
  additionalFiles: unknown[];
  ideTemplateMacros?: unknown;
  resourceSynthesizers: unknown[];
  lastUpgradeCheck?: unknown;
  type: RawProjectType;
  description: string;
  debugDescription: string;
  defaultDebugBuildConfigurationName: string;
}

export interface RawTarget {
  validSourceCompatibleFolderExtensions: string[];
  validSourceExtensions: string[];
  validResourceExtensions: string[];
  validResourceCompatibleFolderExtensions: string[];
  validFolderExtensions: string[];
  name: string;
  destinations: unknown;
  product: RawProduct;
  bundleId: string;
  productName: string;
  deploymentTargets: unknown;
  infoPlist?: unknown;
  entitlements?: unknown;
  settings?: unknown;
  dependencies: unknown[];
  sources: unknown[];
  resources: unknown;
  copyFiles: unknown[];
  headers?: unknown;
  coreDataModels: unknown[];
  scripts: unknown[];
  environmentVariables: unknown;
  launchArguments: unknown[];
  filesGroup: unknown;
  rawScriptBuildPhases: unknown[];
  playgrounds: string[];
  additionalFiles: unknown[];
  buildRules: unknown[];
  prune: boolean;
  mergedBinaryType: unknown;
  mergeable: boolean;
  onDemandResourcesTags?: unknown;
  metadata: unknown;
  type: unknown;
  packages: string[];
  supportedPlatforms: RawPlatform[];
  preScripts: unknown[];
  postScripts: unknown[];
  supportsCatalyst: boolean;
  shouldIncludeHeadersBuildPhase: boolean;
  supportsSources: boolean;
  isMultiplatform: boolean;
  supportsResources: boolean;
  legacyPlatform: RawPlatform;
  isAppClip: boolean;
  dependencyPlatformFilters: unknown;
}

export interface RawWorkspace {
  path: string;
  xcWorkspacePath: string;
  name: string;
  projects: string[];
  schemes: unknown[];
  ideTemplateMacros?: unknown;
  additionalFiles: unknown[];
  generationOptions: unknown;
}

export interface RawUnsupportedPlatformError {
  input: string;
  description: string;
  errorDescription?: string;
}

// =============================================================================
// Transform Logic
// =============================================================================

function getDependencyKey(dep: RawGraphDependency): string {
  if ('target' in dep) return `target:${dep.target.path}:${dep.target.name}`;
  if ('packageProduct' in dep)
    return `package:${dep.packageProduct.path}:${dep.packageProduct.product}`;
  // xcframework wraps an XCFramework struct in _0 (positional param)
  if ('xcframework' in dep) return `xcframework:${dep.xcframework._0.path}`;
  if ('sdk' in dep) return `sdk:${dep.sdk.name}`;
  if ('framework' in dep) return `framework:${JSON.stringify(dep.framework)}`;
  if ('library' in dep) return `library:${JSON.stringify(dep.library)}`;
  if ('bundle' in dep) return `bundle:${JSON.stringify(dep.bundle)}`;
  if ('macro' in dep) return `macro:${JSON.stringify(dep.macro)}`;
  return `unknown:${JSON.stringify(dep)}`;
}

function getDependencyName(dep: RawGraphDependency): string {
  if ('target' in dep) return dep.target.name;
  if ('packageProduct' in dep) return dep.packageProduct.product;
  if ('xcframework' in dep) {
    const path = dep.xcframework._0.path;
    return path.split('/').pop()?.replace('.xcframework', '') ?? 'Unknown';
  }
  if ('sdk' in dep) return dep.sdk.name.replace('.framework', '');
  return 'Unknown';
}

function getNodeType(dep: RawGraphDependency, name: string): NodeType {
  if ('sdk' in dep) return NodeType.Framework;
  if ('xcframework' in dep) return NodeType.Framework;
  if ('packageProduct' in dep) return NodeType.Package;
  if ('framework' in dep) return NodeType.Framework;
  if ('library' in dep) return NodeType.Library;

  const lowerName = name.toLowerCase();
  if (lowerName.endsWith('tests') || lowerName.endsWith('test')) return NodeType.TestUnit;
  if (lowerName.endsWith('uitests')) return NodeType.TestUi;
  if (lowerName.endsWith('app') || lowerName === 'tuist') return NodeType.App;
  if (lowerName.endsWith('kit') || lowerName.endsWith('core')) return NodeType.Framework;
  if (lowerName.endsWith('cli')) return NodeType.Cli;
  return NodeType.Library;
}

function getOrigin(dep: RawGraphDependency): Origin {
  if ('sdk' in dep) return Origin.External;
  if ('xcframework' in dep) return Origin.External;
  if ('packageProduct' in dep) return Origin.External;

  if ('target' in dep) {
    const path = dep.target.path;
    if (path.includes('.build/registry/downloads/') || path.includes('.build/checkouts/')) {
      return Origin.External;
    }
  }
  return Origin.Local;
}

function getProjectName(dep: RawGraphDependency): string | undefined {
  if ('target' in dep) {
    const parts = dep.target.path.split('/');
    return parts[parts.length - 1] ?? parts[parts.length - 2];
  }
  if ('packageProduct' in dep) {
    const parts = dep.packageProduct.path.split('/');
    return parts[parts.length - 1] ?? parts[parts.length - 2];
  }
  return undefined;
}

function parseAlternatingArray<K, V>(arr: (K | V)[], isKey: (item: K | V) => item is K): Map<K, V> {
  const result = new Map<K, V>();
  for (let i = 0; i < arr.length; i += 2) {
    const key = arr[i];
    const value = arr[i + 1];
    if (key !== undefined && value !== undefined && isKey(key)) {
      result.set(key, value as V);
    }
  }
  return result;
}

function createNode(key: string, name: string, dep: RawGraphDependency): GraphNode {
  const project = getProjectName(dep);
  const node: GraphNode = {
    id: key,
    name: name,
    type: getNodeType(dep, name),
    platform: Platform.macOS,
    origin: getOrigin(dep),
  };
  if (project !== undefined) {
    node.project = project;
  }
  return node;
}

export function transformTuistGraph(raw: RawGraph): GraphData {
  const nodes = new Map<string, GraphNode>();
  const edges: GraphEdge[] = [];

  const deps = parseAlternatingArray<RawGraphDependency, RawGraphDependency[]>(
    raw.dependencies as (RawGraphDependency | RawGraphDependency[])[],
    (item): item is RawGraphDependency => !Array.isArray(item),
  );

  for (const [source, targets] of deps) {
    const sourceKey = getDependencyKey(source);
    const sourceName = getDependencyName(source);

    if (!nodes.has(sourceKey)) {
      nodes.set(sourceKey, createNode(sourceKey, sourceName, source));
    }

    for (const target of targets) {
      const targetKey = getDependencyKey(target);
      const targetName = getDependencyName(target);

      if (!nodes.has(targetKey)) {
        nodes.set(targetKey, createNode(targetKey, targetName, target));
      }

      edges.push({ source: sourceKey, target: targetKey });
    }
  }

  return { nodes: Array.from(nodes.values()), edges };
}

export async function loadTuistGraph(jsonPath: string): Promise<GraphData> {
  const response = await fetch(jsonPath);
  const raw = (await response.json()) as RawGraph;
  return transformTuistGraph(raw);
}
