import type { ClusterPosition } from '@shared/schemas';
import type { ElkExtendedEdge, ElkNode } from 'elkjs/lib/elk-api.js';
import type { ClusterGraph } from '../cluster-graph';
import type { LayoutConfig } from '../config';
import type { MicroLayoutResult } from './micro-layout';

/** ElkNode extended with layout metadata properties generated by ELK */
interface ElkNodeWithLayoutIds extends ElkNode {
  'org.eclipse.elk.layered.layering.layerId'?: number;
  'org.eclipse.elk.layered.crossingMinimization.positionId'?: number;
}

// ============================================================================
// ELK Graph Construction Helpers
// ============================================================================

function buildElkChildren(
  clusterGraph: ClusterGraph,
  microLayouts: Map<string, MicroLayoutResult>,
  config: LayoutConfig,
): ElkNode[] {
  return clusterGraph.nodes.map((cluster) => {
    const micro = microLayouts.get(cluster.id);
    const hierarchyHandling = cluster.elkOptions?.hierarchyHandling ?? config.elkHierarchyHandling;

    return {
      id: cluster.id,
      width: micro?.width ?? config.minClusterSize,
      height: micro?.height ?? config.minClusterSize,
      layoutOptions: {
        'org.eclipse.elk.nodeLabels.placement': 'OUTSIDE V_TOP H_CENTER',
        'elk.hierarchyHandling': hierarchyHandling,
      },
    };
  });
}

function buildElkEdges(clusterGraph: ClusterGraph): ElkExtendedEdge[] {
  return clusterGraph.edges.map((e) => ({
    id: `e_${e.source}_${e.target}`,
    sources: [e.source],
    targets: [e.target],
    layoutOptions: {
      'elk.layered.priority.direction': String(Math.min(10, 1 + Math.log2(e.weight ?? 1))),
      'elk.layered.priority.shortness': String(Math.min(10, 1 + Math.log2(e.weight ?? 1))),
      'elk.edge.thickness': String(1 + Math.log2(e.weight ?? 1)),
    },
  }));
}

function buildElkRoot(
  children: ElkNode[],
  edges: ElkExtendedEdge[],
  config: LayoutConfig,
  elkWidthHint: number,
): ElkNode {
  return {
    id: 'root',
    width: elkWidthHint,
    height: config.elkMaxHeight,
    children,
    edges,
    layoutOptions: {
      'elk.algorithm': 'layered',
      'elk.direction': config.elkDirection,
      'elk.spacing.nodeNode': String(config.elkNodeSpacing),
      'elk.layered.spacing.nodeNodeBetweenLayers': String(config.elkLayerSpacing),
      'elk.edgeRouting': 'POLYLINE',
      'elk.hierarchyHandling': config.elkHierarchyHandling,
      'elk.layered.wrapping.strategy': 'SINGLE_EDGE',
      'elk.layered.nodePlacement.strategy': 'BRANDES_KOEPF',
      'elk.layered.crossingMinimization.strategy': 'LAYER_SWEEP',
      'elk.layered.layering.strategy': 'MIN_WIDTH',
      'elk.layered.layering.minWidth.upperBoundOnWidth': String(elkWidthHint),
      'org.eclipse.elk.layered.generatePositionAndLayerIds': 'true',
    },
  };
}

// ============================================================================
// Post-Compaction Helpers
// ============================================================================

function groupIntoBands(
  layoutChildren: ElkNodeWithLayoutIds[],
  ySnap: number,
): Map<number, ElkNodeWithLayoutIds[]> {
  const bands = new Map<number, ElkNodeWithLayoutIds[]>();

  for (const node of layoutChildren) {
    let bandIndex = node['org.eclipse.elk.layered.layering.layerId'];

    if (typeof bandIndex !== 'number') {
      const cy = (node.y ?? 0) + (node.height ?? 0) / 2;
      bandIndex = Math.floor(cy / ySnap);
    }

    if (!bands.has(bandIndex)) bands.set(bandIndex, []);
    bands.get(bandIndex)!.push(node);
  }

  return bands;
}

function sortBandNodes(nodes: ElkNodeWithLayoutIds[]): void {
  nodes.sort((a, b) => {
    const posA = a['org.eclipse.elk.layered.crossingMinimization.positionId'];
    const posB = b['org.eclipse.elk.layered.crossingMinimization.positionId'];
    if (typeof posA === 'number' && typeof posB === 'number') {
      return posA - posB;
    }
    return (a.x ?? 0) - (b.x ?? 0);
  });
}

function getEffectiveDiameter(node: ElkNode): number {
  return Math.max(node.width ?? 100, node.height ?? 100) + 60;
}

function wrapNodesIntoRows(nodes: ElkNode[], spacing: number, maxWidth: number): ElkNode[][] {
  const rows: ElkNode[][] = [[]];
  let currentRowWidth = 0;

  for (const node of nodes) {
    const wEff = getEffectiveDiameter(node);
    const nextWidth = rows[rows.length - 1]!.length === 0 ? wEff : currentRowWidth + spacing + wEff;

    if (nextWidth > maxWidth && rows[rows.length - 1]!.length > 0) {
      rows.push([]);
      currentRowWidth = wEff;
    } else {
      currentRowWidth = nextWidth;
    }
    rows[rows.length - 1]!.push(node);
  }

  return rows;
}

function layoutRow(row: ElkNode[], spacing: number, currentY: number): void {
  const rowItems = row.map((n) => ({
    node: n,
    r: getEffectiveDiameter(n) / 2,
  }));

  const totalWidth = rowItems.reduce((sum, item, i) => {
    return sum + item.r * 2 + (i < rowItems.length - 1 ? spacing : 0);
  }, 0);

  let currentCX = -totalWidth / 2 + (rowItems[0]?.r ?? 0);

  for (let i = 0; i < rowItems.length; i++) {
    const { node, r } = rowItems[i]!;
    node.x = currentCX - (node.width ?? 0) / 2;
    node.y = currentY - (node.height ?? 0) / 2;

    if (i < rowItems.length - 1) {
      const nextR = rowItems[i + 1]!.r;
      currentCX += r + spacing + nextR;
    }
  }
}

function compactBands(
  layoutChildren: ElkNodeWithLayoutIds[],
  config: LayoutConfig,
  packMaxWidth: number,
): void {
  const bands = groupIntoBands(layoutChildren, config.elkLayerSpacing);
  const sortedBands = Array.from(bands.entries()).sort((a, b) => a[0] - b[0]);

  let yCursor = 0;

  for (const [_, nodes] of sortedBands) {
    sortBandNodes(nodes);

    const rows = wrapNodesIntoRows(nodes, config.elkNodeSpacing, packMaxWidth);
    let currentY = yCursor;

    for (const row of rows) {
      const maxRowH = row.reduce((max, n) => Math.max(max, n.height ?? 100), 0);
      const rowGap = 100;

      layoutRow(row, config.elkNodeSpacing, currentY);
      currentY += maxRowH + rowGap;
    }

    yCursor = currentY + (config.elkLayerSpacing - 100);
  }
}

// ============================================================================
// Position Extraction
// ============================================================================

function extractPositions(layoutChildren: ElkNode[]): Map<string, ClusterPosition> {
  const positions = new Map<string, ClusterPosition>();

  for (const node of layoutChildren) {
    const cx = (node.x ?? 0) + (node.width ?? 0) / 2;
    const cy = (node.y ?? 0) + (node.height ?? 0) / 2;

    positions.set(node.id, {
      id: node.id,
      x: cx,
      y: cy,
      width: node.width ?? 100,
      height: node.height ?? 100,
      nodeCount: 0,
      vx: 0,
      vy: 0,
    });
  }

  return positions;
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Compute macro-layout (inter-cluster) using ELK Layered algorithm
 * "Tectonic Plates" stage
 */
export async function computeMacroLayout(
  clusterGraph: ClusterGraph,
  microLayouts: Map<string, MicroLayoutResult>,
  config: LayoutConfig,
): Promise<Map<string, ClusterPosition>> {
  const { default: ELK } = await import('elkjs/lib/elk.bundled.js');
  const elk = new ELK();
  const elkWidthHint = 10000;

  // 1. Build ELK Graph
  const children = buildElkChildren(clusterGraph, microLayouts, config);
  const edges = buildElkEdges(clusterGraph);
  const root = buildElkRoot(children, edges, config, elkWidthHint);

  // 2. Run Layout
  const layout = await elk.layout(root);

  // 3. Post-Compaction & Centering
  if (layout.children) {
    compactBands(layout.children as ElkNodeWithLayoutIds[], config, elkWidthHint);
  }

  // 4. Extract Positions
  return layout.children ? extractPositions(layout.children) : new Map();
}
