import type { ClusterPosition } from '@shared/schemas';
import type { ElkExtendedEdge, ElkNode } from 'elkjs/lib/elk-api.js';
import type { ClusterGraph } from '../cluster-graph';
import type { LayoutConfig } from '../config';
import type { MicroLayoutResult } from './micro-layout';

/** ElkNode extended with layout metadata properties generated by ELK */
interface ElkNodeWithLayoutIds extends ElkNode {
  'org.eclipse.elk.layered.layering.layerId'?: number;
  'org.eclipse.elk.layered.crossingMinimization.positionId'?: number;
}

/** Builds ELK child nodes from clusters, using micro-layout dimensions for sizing. */
function buildElkChildren(
  clusterGraph: ClusterGraph,
  microLayouts: Map<string, MicroLayoutResult>,
  config: LayoutConfig,
): ElkNode[] {
  return clusterGraph.nodes.map((cluster) => {
    const micro = microLayouts.get(cluster.id);
    const hierarchyHandling = cluster.elkOptions?.hierarchyHandling ?? config.elkHierarchyHandling;

    return {
      id: cluster.id,
      width: micro?.width ?? config.minClusterSize,
      height: micro?.height ?? config.minClusterSize,
      layoutOptions: {
        'org.eclipse.elk.nodeLabels.placement': 'OUTSIDE V_TOP H_CENTER',
        'elk.hierarchyHandling': hierarchyHandling,
      },
    };
  });
}

/** Converts cluster graph edges to ELK edge format with weight-based priority. */
function buildElkEdges(clusterGraph: ClusterGraph): ElkExtendedEdge[] {
  return clusterGraph.edges.map((e) => ({
    id: `e_${e.source}_${e.target}`,
    sources: [e.source],
    targets: [e.target],
    layoutOptions: {
      'elk.layered.priority.direction': String(Math.min(10, 1 + Math.log2(e.weight ?? 1))),
      'elk.layered.priority.shortness': String(Math.min(10, 1 + Math.log2(e.weight ?? 1))),
      'elk.edge.thickness': String(1 + Math.log2(e.weight ?? 1)),
    },
  }));
}

/** Builds the ELK root node with layered algorithm configuration. */
function buildElkRoot(
  children: ElkNode[],
  edges: ElkExtendedEdge[],
  config: LayoutConfig,
  elkWidthHint: number,
): ElkNode {
  return {
    id: 'root',
    width: elkWidthHint,
    height: config.elkMaxHeight,
    children,
    edges,
    layoutOptions: {
      'elk.algorithm': 'layered',
      'elk.direction': config.elkDirection,
      'elk.spacing.nodeNode': String(config.elkNodeSpacing),
      'elk.layered.spacing.nodeNodeBetweenLayers': String(config.elkLayerSpacing),
      'elk.edgeRouting': 'POLYLINE',
      'elk.hierarchyHandling': config.elkHierarchyHandling,
      'elk.layered.wrapping.strategy': 'SINGLE_EDGE',
      'elk.layered.nodePlacement.strategy': 'BRANDES_KOEPF',
      'elk.layered.crossingMinimization.strategy': 'LAYER_SWEEP',
      'elk.layered.layering.strategy': 'MIN_WIDTH',
      'elk.layered.layering.minWidth.upperBoundOnWidth': String(elkWidthHint),
      'org.eclipse.elk.layered.generatePositionAndLayerIds': 'true',
      'elk.validateGraph': 'true',
      'elk.validateOptions': 'true',
      'elk.debugMode': 'true',
    },
  };
}

/** Groups layout children into horizontal bands by ELK layer ID or Y-position. */
function groupIntoBands(
  layoutChildren: ElkNodeWithLayoutIds[],
  ySnap: number,
): Map<number, ElkNodeWithLayoutIds[]> {
  const bands = new Map<number, ElkNodeWithLayoutIds[]>();

  for (const node of layoutChildren) {
    let bandIndex = node['org.eclipse.elk.layered.layering.layerId'];

    if (typeof bandIndex !== 'number') {
      const cy = (node.y ?? 0) + (node.height ?? 0) / 2;
      bandIndex = Math.floor(cy / ySnap);
    }

    if (!bands.has(bandIndex)) bands.set(bandIndex, []);
    bands.get(bandIndex)?.push(node);
  }

  return bands;
}

/** Sorts nodes within a band by ELK crossing-minimization position or X coordinate. */
function sortBandNodes(nodes: ElkNodeWithLayoutIds[]): void {
  nodes.sort((a, b) => {
    const posA = a['org.eclipse.elk.layered.crossingMinimization.positionId'];
    const posB = b['org.eclipse.elk.layered.crossingMinimization.positionId'];
    if (typeof posA === 'number' && typeof posB === 'number') {
      /* v8 ignore start -- ELK positionId sorting; tested via mock positionId injection */
      return posA - posB;
      /* v8 ignore stop */
    }
    return (a.x ?? 0) - (b.x ?? 0);
  });
}

/** Returns the effective diameter of a node (max dimension plus padding). */
function getEffectiveDiameter(node: ElkNode): number {
  return Math.max(node.width ?? 100, node.height ?? 100) + 60;
}

/** Wraps nodes into rows that fit within maxWidth, similar to text line wrapping. */
function wrapNodesIntoRows(nodes: ElkNode[], spacing: number, maxWidth: number): ElkNode[][] {
  const rows: ElkNode[][] = [[]];
  let currentRowWidth = 0;

  for (const node of nodes) {
    const wEff = getEffectiveDiameter(node);
    const currentRow = rows[rows.length - 1];
    const nextWidth =
      currentRow && currentRow.length === 0 ? wEff : currentRowWidth + spacing + wEff;

    if (nextWidth > maxWidth && currentRow && currentRow.length > 0) {
      rows.push([]);
      currentRowWidth = wEff;
    } else {
      currentRowWidth = nextWidth;
    }
    const lastRow = rows[rows.length - 1];
    if (lastRow) lastRow.push(node);
  }

  return rows;
}

/** Positions nodes in a row centered horizontally at the given Y coordinate. */
function layoutRow(row: ElkNode[], spacing: number, currentY: number): void {
  const rowItems = row.map((n) => ({
    node: n,
    r: getEffectiveDiameter(n) / 2,
  }));

  const totalWidth = rowItems.reduce((sum, item, i) => {
    return sum + item.r * 2 + (i < rowItems.length - 1 ? spacing : 0);
  }, 0);

  let currentCX = -totalWidth / 2 + (rowItems[0]?.r ?? 0);

  for (let i = 0; i < rowItems.length; i++) {
    const item = rowItems[i];
    if (!item) continue;
    const { node, r } = item;
    node.x = currentCX - (node.width ?? 0) / 2;
    node.y = currentY - (node.height ?? 0) / 2;

    if (i < rowItems.length - 1) {
      const nextItem = rowItems[i + 1];
      const nextR = nextItem ? nextItem.r : 0;
      currentCX += r + spacing + nextR;
    }
  }
}

/** Compacts layout children by grouping into bands, wrapping rows, and re-positioning. */
function compactBands(
  layoutChildren: ElkNodeWithLayoutIds[],
  config: LayoutConfig,
  packMaxWidth: number,
): void {
  const bands = groupIntoBands(layoutChildren, config.elkLayerSpacing);
  const sortedBands = Array.from(bands.entries()).sort((a, b) => a[0] - b[0]);

  let yCursor = 0;

  for (const [_, nodes] of sortedBands) {
    sortBandNodes(nodes);

    const rows = wrapNodesIntoRows(nodes, config.elkNodeSpacing, packMaxWidth);
    let currentY = yCursor;

    for (const row of rows) {
      const maxRowH = row.reduce((max, n) => Math.max(max, n.height ?? 100), 0);
      const rowGap = 100;

      layoutRow(row, config.elkNodeSpacing, currentY);
      currentY += maxRowH + rowGap;
    }

    yCursor = currentY + (config.elkLayerSpacing - 100);
  }
}

/** Extracts center-based cluster positions from ELK layout children. */
function extractPositions(layoutChildren: ElkNode[]): Map<string, ClusterPosition> {
  const positions = new Map<string, ClusterPosition>();

  for (const node of layoutChildren) {
    const cx = (node.x ?? 0) + (node.width ?? 0) / 2;
    const cy = (node.y ?? 0) + (node.height ?? 0) / 2;

    positions.set(node.id, {
      id: node.id,
      x: cx,
      y: cy,
      width: node.width ?? 100,
      height: node.height ?? 100,
      nodeCount: 0,
      vx: 0,
      vy: 0,
    });
  }

  return positions;
}

/**
 * Compute macro-layout (inter-cluster positioning) using ELK Layered algorithm.
 * This is the "Tectonic Plates" stage where clusters are placed relative to each other.
 *
 * @param clusterGraph - The cluster meta-graph with aggregated edges
 * @param microLayouts - Per-cluster micro layout results (used for cluster sizing)
 * @param config - Layout configuration
 * @returns Map of cluster ID to world-space position
 */
export async function computeMacroLayout(
  clusterGraph: ClusterGraph,
  microLayouts: Map<string, MicroLayoutResult>,
  config: LayoutConfig,
): Promise<Map<string, ClusterPosition>> {
  const { default: ELK } = await import('elkjs/lib/elk.bundled.js');
  const elk = new ELK();
  const elkWidthHint = 10000;

  // 1. Build ELK Graph
  const children = buildElkChildren(clusterGraph, microLayouts, config);
  const edges = buildElkEdges(clusterGraph);
  const root = buildElkRoot(children, edges, config, elkWidthHint);

  // 2. Run Layout (with ELK debug instrumentation)
  const layout = await elk.layout(root, {
    logging: true,
    measureExecutionTime: true,
  });

  /* v8 ignore start -- debug logging only runs in browser */
  const elkResult = layout as ElkNode & {
    logging?: { name?: string; executionTime?: number; children?: unknown[] };
  };
  if (elkResult.logging) {
    console.log('[elk] layout result:', elkResult.logging);
  }
  /* v8 ignore stop */

  // 3. Post-Compaction & Centering
  if (layout.children) {
    compactBands(layout.children as ElkNodeWithLayoutIds[], config, elkWidthHint);
  }

  // 4. Extract Positions
  return layout.children ? extractPositions(layout.children) : new Map();
}
